config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  # 顧客側ルーティング
  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get "post_likes"
      end
      collection do
        get "check"
      end
      resources :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only: [:new, :show, :create, :destroy] do
      collection do
        get "ranking"
      end
        resource :post_likes, only: [:create, :destroy]
        resources :post_comments, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
  end

  # 管理者側ルーティング
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:show, :edit, :update] do
      member do
        patch "ban"
      end
    end
    resources :posts, only: [:index, :show, :destroy]
    resources :categories, only: [:index, :create] do
      collection do
        get "edit"
        patch "update", as: :update
      end
    end
  end

  # 検索用ルーティング
  get "search" => "searches#search"
  get "search_result" => "searches#search_result"

  # ゲストログイン用のルーティング
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end


end


# 次回やること
# ・通知機能の非同期化

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def search
    @categories = Category.all
  end
  
  def search_result
    @word = params[:word]
    @range = params[:range]
    if @range == "ユーザー名"
      @results = User.partial_search(@word).page(params[:page]).per(20)
    else
      @results = Post.partial_search(@word).page(params[:page]).per(8)
    end
  end
  
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 mx-auto">
      <h4>【検索】</h4>
      <div class="mt-5 mb-3 heading col-2">キーワード検索</div>
      <div class="search_form mt-2">
        <%= form_with url: search_result_path, local: true, method: :get do |f| %>
          <%= f.text_field :word %>
          <%= f.select :range, options_for_select([['ユーザー名'], ['投稿']]) %>
          <%= f.hidden_field :method, value: "partial" %>
          <%= f.submit "検索", class: "btn-sm btn-light border" %>
        <% end %>
      </div>
      <div class="mt-5 mb-3 heading col-2">ジャンル検索</div>
      <% @categories.each do |category| %>
        <% if user_signed_in? %>
          <%= link_to root_path(category_id: category.id), class: "btn btn-light border mt-2" do %>
            <%= category.name %>
          <% end %>
        <% else %>
          <%= link_to admin_posts_path(category_id: category.id), class: "btn btn-light border mt-2" do %>
            <%= category.name %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/searches/search_result.html.erb
<div class="container">
  <div>
    "<%= @word %>"の検索結果
    <% if @results.exists? %>
      （全<%= @results.total_count %>件中<%= @results.offset_value + 1 %>〜<%= @results.offset_value + @results.length %>件を表示しています。）
    <% end %>
  </div>
  <div class="col-lg-12 mx-auto">
    <% if @results.present? %>
      <% if @range == "ユーザー名" %>
        <% @results.each do |result| %>
          <% if user_signed_in? %>
            <%= link_to user_path(result.id), class: "link" do %>
              <table class="table table-borderless post">
                <tbody>
                  <tr>
                    <td>
                      <span class="mx-4 my-5">
                        <%= image_tag result.get_user_image(80,80) %>
                      </span>
                      <span class="d-inline-block text-truncate mx-5">
                        <%= result.name %>
                      </span>
                    </td>
                    <td>
                      <span class="mx-2 mx-md-5 text-left d-inline-block">
                        <% if result.profile.present? %>
                          <%= result.profile %>
                        <% else %>
                          プロフィールはまだありません。
                        <% end %>
                      </span>
                    </td>
                  </tr>
                </tbody>
              </table>
            <% end %>
            <div class="border my-3"></div>
          <% else %>
            <%= link_to admin_user_path(result.id), class: "link" do %>
              <table class="table table-borderless">
                <thead>
                  <tr>
                    <th style="width: 40%"></th>
                    <th style="width: 60%"></th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      <%= image_tag result.get_user_image(80,80) %>
                      <span class="d-inline-block text-truncate mx-5">
                        <%= result.name %>
                      </span>
                    </td>
                    </td>
                    <td>
                      <% if result.profile.present? %>
                        <%= result.profile %>
                      <% else %>
                        プロフィールはまだありません。
                      <% end %>
                    </td>
                  </tr>
                </tbody>
              </table>
            <% end %>
            <div class="border my-3"></div>
          <% end %>
        <% end %>
      <% else %>
        <div class="row">
          <% @results.each do |result| %>
            <div class="col-3 mt-3 px-1">
              <% if user_signed_in? %>
                <div class="card shadow">
                  <%= link_to post_path(result.id), class: "card h-100 w-70 link" do %>
                    <div class="card-body">
                      <table class="table table-borderless">
                        <tr>
                          <td>
                            <%= image_tag result.get_post_image(100,100), size: "100x100", class: "rounded border" %>
                            <span class="d-inline-block text-truncate ml-1">
                              <%= result.user.name %>
                            </span>
                          </td>
                        </tr>
                      </table>
                      <div class="card-text">
                        <h6 class="border p-md-1">
                          <%= truncate(result.text, length: 32) %>
                        </h6>
                      </div>
                    </div>
                    <div class="card-footer">
                      <ul class="list-group list-group-flush">
                        <li class="list-group-item">ジャンル:<%= result.category.name %></li>
                        <li class="list-group-item">
                          <% if result.post_liked_by?(current_user) %>
                            <span class="btn btn-sm btn-light rounded-pill border">へぇ〜済</span>
                          <% else %>
                            <span class="btn btn-sm btn-light rounded-pill border">へぇ〜</span>
                          <% end %>
                          :<%= result.post_likes.count %>件
                        </li>
                        <li class="list-group-item">コメント:<%= result.post_comments.count %>件</li>
                      </ul>
                    </div>
                  <% end %>
                </div>
              <% else %>
                <%= link_to admin_post_path(result.id), class: "card h-100 w-70 link" do %>
                  <div class="card-body">
                    <table class="table table-borderless">
                      <tr>
                        <td>
                          <%= image_tag result.get_post_image(100,100), size: "100x100", class: "rounded border" %>
                          <span class="d-inline-block text-truncate ml-1">
                            <%= result.user.name %>
                          </span>
                        </td>
                      </tr>
                    </table>
                    <div class="card-text">
                      <h6 class="border p-md-1">
                        <%= truncate(result.text, length: 32) %>
                      </h6>
                    </div>
                  </div>
                  <div class="card-footer">
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item">ジャンル:<%= result.category.name %></li>
                      <li class="list-group-item">
                        <span class="btn btn-sm btn-light rounded-pill border">へぇ〜</span>:<%= result.post_likes.count %>件
                      </li>
                      <li class="list-group-item">コメント:<%= result.post_comments.count %>件</li>
                    </ul>
                  </div>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <% if @range == "ユーザー名" %>
        <div>該当するユーザーはいません。</div>
      <% else %>
        <div>該当する投稿はありません。</div>
      <% end %>
    <% end %>
    <div class="d-flex justify-content-center mt-3 custom-pagination">
      <%= paginate @results %>
    </div>
  </div>
</div>