config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  # 顧客側ルーティング
  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get "post_likes"
      end
      collection do
        get "check"
      end
      resources :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only: [:new, :show, :create, :destroy] do
      collection do
        get "ranking"
      end
        resource :post_likes, only: [:create, :destroy]
        resources :post_comments, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
  end

  # 管理者側ルーティング
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:show, :edit, :update] do
      member do
        patch "ban"
      end
    end
    resources :posts, only: [:index, :show, :destroy]
    resources :categories, only: [:index, :create] do
      collection do
        get "edit"
        patch "update", as: :update
      end
    end
  end

  # 検索用ルーティング
  get "search" => "searches#search"
  get "search_result" => "searches#search_result"

  # ゲストログイン用のルーティング
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end


end


# 次回やること
# ・通知機能の非同期化

app/models/category.rb
class Category < ApplicationRecord
  
  # アソシエーション
  has_many :posts
  
  # バリデーション
  validates :name, presence: true
  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @category = Category.new
    @categories = Category.all
  end

  def edit
    @categories = Category.all
  end

  def update
    @categories = Category.all
    @categories_values = params[:category].values
    @categories.zip(@categories_values) do |category, value|
      category.update(name: value)
    end
    redirect_to admin_categories_path
    flash[:notice] = "変更内容を保存しました"

  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "ジャンルを追加しました"
      redirect_to request.referer
    else
      @categories = Category.all
      render :index
    end
  end


  private

  def category_params
    params.require(:category).permit(:name, :id)
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 mx-auto">

      <h4>【ジャンル編集】</h4>
      <%= form_with model: @categories, url: update_admin_categories_path, method: :patch do |f| %>
        <% @categories.each_with_index do |category, i| %>
          <span class="btn btn-light border mt-2">
            <%= f.text_field "name_#{i}".to_sym, value: category.name %>
          </span>
        <% end %>
        <div class="text-center">
          <%= f.submit "編集を保存する", class: "btn btn-success mt-5" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 mx-auto">
      <%= render "layouts/errors", model: @category %>
      <h4>【ジャンルの新規登録】</h4>
      <div class="text-center my-5">
        <%= form_with model: @category, url: admin_categories_path do |f| %>
          <%= f.text_field :name, placeholder: "ジャンル名" %>
          <%= f.submit "追加する", class: "btn btn-info" %>
        <% end %>
      </div>

      <h4>【ジャンル一覧】</h4>
      <% @categories.each do |category| %>
        <span class="btn btn-light border mt-2">
          <%= category.name %>
        </span>
      <% end %>
      <div class="text-center">
        <%= link_to "編集する", edit_admin_categories_path, class: "btn btn-success mt-5" %>
      </div>
    </div>
  </div>
</div>