config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  # 顧客側ルーティング
  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get "post_likes"
      end
      collection do
        get "check"
      end
      resources :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only: [:new, :show, :create, :destroy] do
      collection do
        get "ranking"
      end
        resource :post_likes, only: [:create, :destroy]
        resources :post_comments, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
  end

  # 管理者側ルーティング
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:show, :edit, :update] do
      member do
        patch "ban"
      end
    end
    resources :posts, only: [:index, :show, :destroy]
    resources :categories, only: [:index, :create] do
      collection do
        get "edit"
        patch "update", as: :update
      end
    end
  end

  # 検索用ルーティング
  get "search" => "searches#search"
  get "search_result" => "searches#search_result"

  # ゲストログイン用のルーティング
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end


end


# 次回やること
# ・通知機能の非同期化

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # アソシエーション
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :post_likes, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :active_notifications, class_name: "Notification", foreign_key: "visitor_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  # バリデーション
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :profile, length: { maximum: 100 }

  # 画像の添付
  has_one_attached :user_image

  # ユーザ画像のリサイズとNO_IMAGE
  def get_user_image(width,height)
    unless user_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      user_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    user_image.variant(resize_to_limit: [width, height]).processed
  end

  # フォローしたとき
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すとき
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # 部分一致検索の条件
  def self.partial_search(word)
    if word.present?
      where("name LIKE ?", '%' + word + '%')
    else
      none
    end
  end

  # ゲストログイン
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  # フォロー時のアクション（通知機能）
  def create_notification_follow(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ?", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
        )
    end
    notification.save if notification.valid?
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "変更を保存しました"
      redirect_to admin_user_path(@user.id)
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:id, :name, :email, :user_status, :user_image, :profile)
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :check_guest, only: [:destroy, :update]

  def check_guest
    if resource.email == "guest@example.com"
      redirect_to root_path, notice: "ゲストユーザーは編集・削除できません"
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 mx-auto">
      <h3>【ユーザー編集】</h3>
      <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>
        <table class="table table-borderless text-center">
          <tr>
            <td>ユーザーID</td>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <td><%= f.label :name, "ユーザーネーム" %></td>
            <td><%= f.text_field :name, class: "form-control" %></td>
          </tr>
          <tr>
            <td><%= f.label :email, "メールアドレス" %></td>
            <td><%= f.text_field :email, class: "form-control" %></td>
          </tr>
          <tr>
            <td><%= f.label :user_status, "ユーザーステータス" %></td>
            <td>
              <%= f.radio_button :user_status, false %><%= f.label :通常 %>
              <%= f.radio_button :user_status, true %><%= f.label :停止 %>
            </td>
          </tr>
          <tr>
            <td><%= f.label :user_image, "ユーザー写真" %></td>
            <td><%= image_tag @user.get_user_image(100,100) %></td>
            <td><%= f.file_field :user_image %></td>
          </tr>
          <tr>
            <td><%= f.label :profile, "プロフィール" %></td>
            <td><%= f.text_field :profile, class: "form-control" %></td>
          </tr>
        </table>
        <div class="text-center">
          <%= f.submit "変更を保存する", class: "btn btn-warning" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 mx-auto border-bottom">
      <h3>【ユーザー詳細】</h3>
      <table class="table table-borderless">
        <thead>
          <tr>
            <th style="width: 40%"></th>
            <th style="width: 60%"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span class="mx-5">
                <%= image_tag @user.get_user_image(100,100) %>
              </span>
              <span class="d-inline-block text-truncate mx-5">
                <%= @user.name %>
              </span>
            </td>
            <td class="border border-secondary">
              <span class="mx-2 mx-md-5 text-left d-inline-block">
                <% if @user.profile.present? %>
                  <%= @user.profile %>
                <% else %>
                  <span class="mx-2">
                    プロフィールはまだありません。
                  </span>
                <% end %>
              </span>
            </td>
          </tr>
        </tbody>
      </table>
      <div class= "text-center" >
        <table class="table table-borderless">
          <tr>
            <td>ユーザーID</td>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <td>ユーザーネーム</td>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <td>ユーザーステータス</td>
            <td>
              <% if @user.user_status == false %>
                <span class="text-success">通常</span>
              <% else %>
                <span class="text-danger">停止</span>
              <% end %>
            </td>
          </tr>
        </table>
      </div>


      <div class="text-center mb-3">
        <%= link_to "編集する", edit_admin_user_path(@user.id), class: "btn btn-default" %>
        <br>
        <!--このユーザーの投稿一覧ボタン＝＞検索結果と同じ画面-->
      </div>