config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  # 顧客側ルーティング
  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get "post_likes"
      end
      collection do
        get "check"
      end
      resources :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only: [:new, :show, :create, :destroy] do
      collection do
        get "ranking"
      end
        resource :post_likes, only: [:create, :destroy]
        resources :post_comments, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
  end

  # 管理者側ルーティング
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:show, :edit, :update] do
      member do
        patch "ban"
      end
    end
    resources :posts, only: [:index, :show, :destroy]
    resources :categories, only: [:index, :create] do
      collection do
        get "edit"
        patch "update", as: :update
      end
    end
  end

  # 検索用ルーティング
  get "search" => "searches#search"
  get "search_result" => "searches#search_result"

  # ゲストログイン用のルーティング
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end


end


# 次回やること
# ・通知機能の非同期化

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <ul class="alert alert-danger" role="alert">
    <h6 class="alert-heading">
      <%= model.errors.count %>件のエラーが発生しました
    </h6>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_notification.html.erb
<%= link_to notifications_path, remote: true, class: "btn btn-default nav-link ml-2 shadow notification" do %>
  <% if unchecked_notifications.any? %>
    <span class="fa-stack">
      <i class="fa-regular fa-bell fa-stack-2x" style="font-size: 1.5em;"></i>
      <i class="fa-solid fa-circle n-circle fa-stack-1x"></i>
    </span>
  <% else %>
    <i class="fa-regular fa-bell" style="font-size: 1.5em;"></i>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trivian</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/224a897d7c.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg">
        <div class="container border-bottom border-dark">
          <h1><%= link_to "Trivian", root_path, class: "link" %></h1>
          <ul class="navbar-nav ml-auto p-3">
            <% if user_signed_in? %>
              <li class="nav-item"><%= link_to "About", about_path, class: "btn btn-default nav-link ml-2 shadow" %></li>
              <li class="nav-item"><%= link_to "マイページ", user_path(current_user.id), class: "btn btn-default nav-link ml-2 shadow" %></li>
              <li class="nav-item"><%= link_to "ホーム", root_path, class: "btn btn-default nav-link ml-2 shadow" %></li>
              <li class="nav-item"><%= link_to "検索", search_path, class: "btn btn-default nav-link ml-2 shadow" %></li>
              <li class="nav-item"><%= link_to "ランキング", ranking_posts_path, class: "btn btn-default nav-link ml-2 shadow" %></li>
              <li class="nav-item"><%= link_to "ヘぇ〜一覧", post_likes_user_path(current_user.id), class: "btn btn-default nav-link ml-2 shadow" %></li>
              <li class="nav-item"><%= link_to "投稿する", new_post_path, class: "btn btn-default nav-link ml-2 shadow" %></li>
              <li class="nav-item">
                <%= link_to notifications_path, remote: true, class: "btn btn-default nav-link ml-2 shadow notification" do %>
                  <% if unchecked_notifications.any? %>
                    <span class="fa-stack">
                      <i class="fa-regular fa-bell fa-stack-2x" style="font-size: 1.5em;"></i>
                      <i class="fa-solid fa-circle n-circle fa-stack-1x"></i>
                    </span>
                  <% else %>
                    <i class="fa-regular fa-bell" style="font-size: 1.5em;"></i>
                  <% end %>
                <% end %>
              </li>
            <% elsif admin_signed_in? %>
              <li class="nav-item"><%= link_to "ジャンル一覧", admin_categories_path, class: "btn btn-default nav-link ml-2 shadow" %></li>
              <li class="nav-item"><%= link_to "ユーザー一覧", admin_root_path, class: "btn btn-default nav-link ml-2 shadow" %></li>
              <li class="nav-item"><%= link_to "投稿一覧", admin_posts_path, class: "btn btn-default nav-link ml-2 shadow" %></li>
              <li class="nav-item"><%= link_to "検索", search_path, class: "btn btn-default nav-link ml-2 shadow" %></li>
              <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-default nav-link ml-2 shadow" %></li>
            <% else %>
              <li class="nav-item"><%= link_to "About", about_path, class: "btn btn-default nav-link ml-2 shadow" %></li>
              <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class: "btn btn-default nav-link ml-2 shadow" %></li>
              <li class="nav-item"><%= link_to "新規登録", new_user_registration_path, class: "btn btn-default nav-link ml-2 shadow" %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <main>
      <div class = "container px-5 px-sm-0">
        <div class = "row">
          <div class = "col-auto mt-2 flash">
            <%= flash[:notice] %>
          </div>
        </div>
      </div>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5 border-top">
        <div class="row">
          <div class="mx-auto text-center">
            <h3><%= link_to "Trivian", root_path, class: "link" %></h3>
            <h5>
              <i class="fa-brands fa-instagram"></i>
              <i class="fa-brands fa-facebook-f"></i>
              <i class="fa-brands fa-threads"></i>
              <i class="fa-brands fa-x-twitter"></i>
              <i class="fa-brands fa-tiktok"></i>
              <i class="fa-brands fa-line"></i>
            </h5>
            <p>©CopyRight Trivian.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/create.js.erb
$(".notification").html("<%= j(render 'layouts/notification') %>");

app/views/layouts/destroy.js.erb
$(".notification").html("<%= j(render 'layouts/notification') %>");